server:
  # web端口
  port: 6665

logging:
  level:
    org.springframework.*: info
    org.apache.http.*: error
    org.hibernate.*: error
    com.github.*: debug

spring:
  gson:
    field-naming-policy: lower_case_with_underscores
  groovy:
    template:
      check-template-location: false

secretary:
  # 酷Q配置
  cool:
    # 消息发送地址
    url: http://192.168.2.86:5700
    # 消息token
    token: Mgep4rV49rM8Jf
    # 用于jira&gitlab webhooks消息发送
    # 工作群/讨论组id 1575716762
    groupId: 1575716762
    # 群类型 discuss/group
    groupType: discuss
  # 茉莉机器人配置
  itpk:
    url: http://i.itpk.cn
    apiKey: f5c89b45e875434b4be5d1bd54266db6
    apiSecret: 3xj9lxqied51
  # jira配置
  jira:
    # jira url
    url: http://192.168.2.10:8088
    token: aGFpLnhpZToxMjM0NTY
    # 用户名和qq关系
    users:
      Admin: 412810549
      ying.huang: 410571470
      xiaoling.gou: 1579231853
      xin.yang: 1786370596
      hai.xie: 304560216
      fuwei.liu: 1021901278
      peng.tao: 240098498
      kai.liu: 1186578324
      yiming.liu: 530265498
      weibo.liu: 804912547
    jql:
      # 个人未完成任务
      user_task: assignee = %s AND status not in (验证通过, 关闭, done, 完成) AND type not in (故障, 建议) ORDER BY createdDate DESC
      # 个人未完成bug
      user_bug: assignee = %s AND status not in (验证通过, 关闭, done, 完成) AND type in (故障, 建议) ORDER BY createdDate DESC