server:
  # web端口
  port: 6666

logging:
  level:
    org.springframework.*: info
    org.apache.http.*: error
    org.hibernate.*: error
    com.github.*: debug

spring:
  # gson属性驼峰转下划线
  gson:
    field-naming-policy: lower_case_with_underscores
  groovy:
    template:
      check-template-location: false
  # json message converter优先使用
  http:
    converters:
      preferred-json-mapper: gson

secretary:
  # 酷Q配置
  cool:
    # 消息发送地址
    url: http://192.168.2.86:5700
    # 消息token
    token: Mgep4rV49rM8Jf
    # 用于jira&gitlab webhooks消息发送
    # 工作群/讨论组id 1575716762
    groupId: 854272155
    # 群类型 discuss/group
    groupType: group
  # 茉莉机器人配置
  itpk:
    # 机器人对话服务器url
    url: http://i.itpk.cn
    # 机器人设置服务器url
    robot_url: http://www.itpk.cn
    # 机器人设置用户名
    email: xie__hai@126.com
    apiKey: f5c89b45e875434b4be5d1bd54266db6
    apiSecret: 3xj9lxqied51
  # 百度api配置
  baidu:
    # 翻译api
    translate:
      url: http://api.fanyi.baidu.com
      appId: 20181227000252527
      appSecret: JgnhGnO21vHqBu25hGbz
  # jira配置
  jira:
    # jira url
    url: http://192.168.2.10:8088
    token: aGFpLnhpZToxMjM0NTY
    # 用户名和qq关系
    users:
      hai.xie: 304560216
      hanbing.hu: 648273818
      jie.bai: 1045516761
      shuai.liu: 1462673959
      yangyue: 1468032960
      jingyu.xiao: 1173853143
      xu.liao: 463189296
    # 为bug的issue类型
    bugTypeIds: 10004,10005
    # 开发完成节点包括任务及bug
    doneTransitions: 3,10002
    jql:
      # 个人未完成问题
      user_issue: assignee = %s AND status not in (验证通过, 关闭, done, 完成) ORDER BY createdDate DESC
      # 个人未完成任务
      user_task: assignee = %s AND status not in (验证通过, 关闭, done, 完成) AND type not in (故障, 建议) ORDER BY createdDate DESC
      # 个人未完成bug
      user_bug: assignee = %s AND status not in (验证通过, 关闭, done, 完成) AND type in (故障, 建议) ORDER BY createdDate DESC
  gitlab:
    # jira url
    url: http://192.168.2.20
    token: PASfxcDM_a-4C-LNMH_K
    # 部署环境
    deploy:
      - key: 成铁教务
        token: 30df6856d2b8c7928c809d91205ed5
        ref: dev
        projectId: 44
        env: ALIYUN_EMS
        desc: 成铁阿里云教务
      - key: 南充教务
        token: 617f29ffa59583f75799409d08e970
        ref: dev
        env: ALIYUN_EMS
        projectId: 16
        desc: 南充阿里云教务
      - key: 南充评教
        token: 617f29ffa59583f75799409d08e970
        ref: dev
        env: ALIYUN_EVALUATE
        projectId: 16
        desc: 南充阿里云评教
      - key: 昆卫教务
        token: 617f29ffa59583f75799409d08e970
        ref: kunwei
        env: 12_SM
        projectId: 16
        desc: 昆卫12环境教务